Description:  CloudFormayion Custom Reource to help with Amazon WorkSpaces creation

Parameters:
  Tag:
    Description: We tag all AWS resources for your convinience.
    Type: String

  DirectoryId:
    Description: Provide existing AWS Directory Service Id.
    Type: String

Resources:
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSLambdaExecute
      Policies:
        -
          PolicyName: !Ref AWS::StackName
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              # grant the ability to enable Amazon WorkDocs for users within Amazon WorkSpaces
              # https://docs.aws.amazon.com/workspaces/latest/adminguide/workspaces-access-control.html
              -
                Effect: Allow
                Action:
                  - ds:DescribeDirectories
                Resource: '*'
              -
                Effect: Allow
                Action:
                  - ds:ListAuthorizedApplications
                  - ds:AuthorizeApplication
                  - ds:UnauthorizeApplication
                Resource: !Sub arn:aws:ds:${AWS::Region}:${AWS::AccountId}:directory/${DirectoryId}
              -
                Effect: Allow
                Action:
                  - workspaces:*
                  - workdocs:RegisterDirectory
                  - workdocs:DeregisterDirectory
                  - workdocs:AddUserToGroup
                  - workdocs:RemoveUserFromGroup
                  - kms:ListAliases
                  - kms:ListKeys
                Resource: '*'

  Lambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Code:
        ZipFile: !Sub |
          'use strict';
          const AWS   = require('aws-sdk');
          const workspaces = new AWS.WorkSpaces();
          const https = require("https");
          const url = require("url");

          exports.handler = async (event, context) => {
            console.log(JSON.stringify(event));
            const { DirectoryId, SubnetIds } = event.ResourceProperties;

            try {
              if (event.RequestType === 'Create') {
                await workspaces.registerWorkspaceDirectory({
                  DirectoryId,
                  SubnetIds,
                  EnableWorkDocs: false
                }).promise();
                const { Directories } = await workspaces.describeWorkspaceDirectories({
                  DirectoryIds: [DirectoryId]
                }).promise();
                console.log(Directories[0].State);
              }
              if (event.RequestType === 'Delete') {
                await workspaces.deregisterWorkspaceDirectory({
                  DirectoryId
                }).promise();
              }
            } catch(err) {
              console.error(err);
              console.error(err.code);
              console.error(event.RequestType);
              if !(err.code === 'ResourceNotFoundException' && event.RequestType === 'Delete') {
                await cfnResponse(event, 'FAILED', context.logStreamName, err.message);
              }
            }
            await cfnResponse(event, 'SUCCESS', context.logStreamName, 'SUCCESS');
            return;
          };

          async function cfnResponse (event, responseStatus, PhysicalResourceId, Reason) {
            return new Promise((resolve, reject) => {
              const responseBody = JSON.stringify({
                Status: responseStatus,
                Reason,
                PhysicalResourceId,
                StackId: event.StackId,
                RequestId: event.RequestId,
                LogicalResourceId: event.LogicalResourceId,
                NoEcho: false,
                Data: {}
              });

              const parsedUrl = url.parse(event.ResponseURL);
              const options = {
                hostname: parsedUrl.hostname,
                port: 443,
                path: parsedUrl.path,
                method: "PUT",
                headers: {
                  "content-type": "",
                  "content-length": responseBody.length
                }
              };

              const request = https.request(options, (response) => {
                console.log("Status code: " + response.statusCode);
                console.log("Status message: " + response.statusMessage);
                resolve(response);
              });

              request.on('error', (err) => {
                console.log({ err });
                reject(err);
              });

              request.write(responseBody);
              request.end();
            });
          }
      Tags:
        - Key: App
          Value: !Ref Tag
        - Key: Name
          Value: !Ref Tag

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${Lambda}
      RetentionInDays: 7

Outputs:
  ServiceToken:
    Value: !GetAtt Lambda.Arn
