Description:  >-
  **WARNING** This template creates AWS VPC NAT Gateway.
  You will be billed for the AWS resources used if you create a stack from this template.

Parameters:
  Tag:
    Description: We tag all AWS resources for your convinience.
    Type: String

  DirectoryId:
    Description: Provide existing AWS Directory Service Id.
    Type: String

  PrivateSubnets:
    Description: Choose which private subnets we should deployed to.
    Type: List<AWS::EC2::Subnet::Id>

  BundledId:
    Description: >
      Amazon WorkSpace Bundle Id.
      aws workspaces describe-workspace-bundles --owner AMAZON --query "Bundles[?Name=='Standard with Amazon Linux 2']".
    Type: String

  EnableWorkSpacesServiceToken:
    Description: AWs Lambda ARN which implements CloudFormation Custom Resource
    Type: String

Resources:
  EnableWorkSpaces:
    Type: Custom::CustomResource
    Properties:
      ServiceToken: !Ref EnableWorkSpacesServiceToken
      DirectoryId: !Ref DirectoryId
      SubnetIds:  # we need only 2 subnets (even if more provided)
        - !Select [ 0, !Ref PrivateSubnets ]
        - !Select [ 1, !Ref PrivateSubnets ]

  Workspaces:
    Type: AWS::WorkSpaces::Workspace
    DependsOn: EnableWorkSpaces
    Properties:
      BundleId: !Ref BundledId
      DirectoryId: !Ref DirectoryId
      UserName: String
      WorkspaceProperties:
        ComputeTypeName: STANDARD
        RunningMode: AUTO_STOP
        RunningModeAutoStopTimeoutInMinutes: 60
      Tags:
        - Key: App
          Value: !Ref Tag
        - Key: Name
          Value: !Ref Tag
