Description:  >-
  **WARNING** This template creates AWS VPC NAT Gateway.
  You will be billed for the AWS resources used if you create a stack from this template.

Parameters:
  Tag:
    Description: We tag all AWS resources for your convinience.
    Type: String

  DirectoryId:
    Description: Provide existing AWS Directory Service Id.
    Type: String

  BundledId:
    Description: >
      Amazon WorkSpace Bundle Id.
      aws workspaces describe-workspace-bundles --owner AMAZON --query "Bundles[?Name=='Standard with Amazon Linux 2']".
    Type: String

Resources:
  Workspaces:
    Type: AWS::WorkSpaces::Workspace
    Properties:
      BundleId: !Ref BundledId
      DirectoryId: !Ref DirectoryId
      UserName: String
      WorkspaceProperties:
        ComputeTypeName: STANDARD
        RunningMode: AUTO_STOP
        RunningModeAutoStopTimeoutInMinutes: 60
      Tags:
        - Key: App
          Value: !Ref Tag
        - Key: Name
          Value: !Ref Tag
